/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolucionesRouteImport } from './routes/soluciones'
import { Route as IndustriasRouteImport } from './routes/industrias'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicLeadSubmitRouteImport } from './routes/api/public/lead-submit'

const SolucionesRoute = SolucionesRouteImport.update({
  id: '/soluciones',
  path: '/soluciones',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriasRoute = IndustriasRouteImport.update({
  id: '/industrias',
  path: '/industrias',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadSubmitRoute = ApiPublicLeadSubmitRouteImport.update({
  id: '/api/public/lead-submit',
  path: '/api/public/lead-submit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/industrias': typeof IndustriasRoute
  '/soluciones': typeof SolucionesRoute
  '/api/public/lead-submit': typeof ApiPublicLeadSubmitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/industrias': typeof IndustriasRoute
  '/soluciones': typeof SolucionesRoute
  '/api/public/lead-submit': typeof ApiPublicLeadSubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/industrias': typeof IndustriasRoute
  '/soluciones': typeof SolucionesRoute
  '/api/public/lead-submit': typeof ApiPublicLeadSubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/industrias' | '/soluciones' | '/api/public/lead-submit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/industrias' | '/soluciones' | '/api/public/lead-submit'
  id:
    | '__root__'
    | '/'
    | '/industrias'
    | '/soluciones'
    | '/api/public/lead-submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IndustriasRoute: typeof IndustriasRoute
  SolucionesRoute: typeof SolucionesRoute
  ApiPublicLeadSubmitRoute: typeof ApiPublicLeadSubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/soluciones': {
      id: '/soluciones'
      path: '/soluciones'
      fullPath: '/soluciones'
      preLoaderRoute: typeof SolucionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industrias': {
      id: '/industrias'
      path: '/industrias'
      fullPath: '/industrias'
      preLoaderRoute: typeof IndustriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lead-submit': {
      id: '/api/public/lead-submit'
      path: '/api/public/lead-submit'
      fullPath: '/api/public/lead-submit'
      preLoaderRoute: typeof ApiPublicLeadSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IndustriasRoute: IndustriasRoute,
  SolucionesRoute: SolucionesRoute,
  ApiPublicLeadSubmitRoute: ApiPublicLeadSubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
